version: '3'

services:
  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-12-may-2020/group-projects/capricorn/luna:master
    command: 'sh /scripts/deploy.sh'
    restart: always
    volumes:
      - static-files:/static-files
      - media-files:/media-files
      - frontend:/frontend/build
    depends_on:
      - db
    env_file:
      - env/prod.env

  db:
    image: postgres:12
    env_file:
      - env/prod.env
    volumes:
      - luna_db:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static-files:/static-files
      - media-files:/media-files
      - /etc/letsencrypt:/etc/letsencrypt
      - frontend:/frontend
    depends_on:
      - backend


volumes:
  luna_db:
  static-files:
  media-files:
  frontend:
