version: '3'

services:
  backend:
    image: luna:latest
    #registry.gitlab.propulsion-home.ch/full-stack/batch-12-may-2020/group-projects/capricorn/luna:master
    ports:
      - '9000:8000'
    volumes:
      - ./backend:/backend
      - ./media-files:/media-files
      - ./static-files:/static-files
    command: 'python manage.py runserver 0:8000'
    env_file:
      - env/dev.env
    depends_on:
      - db

  db:
    image: postgres:12
    env_file:
      - env/dev.env
    volumes:
      - luna_db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  luna_db:
  media-files:
  static-files:


